\documentclass{article}
\usepackage{Sweave}
\usepackage{mdframed}
\usepackage[small]{caption}
\setkeys{Gin}{width=0.8\textwidth}
\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm        
\oddsidemargin -0.04cm   
\evensidemargin -0.04cm
\textwidth 16.59cm
\textheight 21.94cm 
%\pagestyle{empty} %comment if want page numbers
\parskip 7.2pt
\renewcommand{\baselinestretch}{1.5}
\parindent 0pt


\begin{document}

\section*{Lecture 14: 23 Oct 2018}
\textbf{Andrew}
\begin{enumerate}
\item Morphospace: butterfly example, where individuals cluster within species. Speciation is the underpinning of descent with modification. 
\item What is a species? 
  \begin{enumerate}
  \item Species is the keystone of evolution. 
  \item Species change, they aren't static, yet discrete. 
  \item Species are groups that are reproductively isolated from other such groups. Biological Species Concept. Ernst Mayr 1942. Gene pool is the sum total of genetic variation in a species. 
  \item Species are essentially are closed gene pools
  \item Wallace essentially stated the same definition in 1864. "when in contact, do not intermix... incapable of producing fertile offspring"
  \end{enumerate}
\item Limitations of Biological Species Concept
  \begin{enumerate}
  \item Fossils: can't test if they can reproduce. Forced to rely on morphological differences
  \item Asexual: even microbes can sometimes reproduce sexually. 
  \item Reproductive Isolation
    \begin{enumerate}
    \item Not always watertight
      \begin{enumerate}
      \item Hybridization among close relatives
      \item They can co-occur. Spatial heterogeneity. 
      \end{enumerate}
    \end{enumerate}
  \end{enumerate}
\item Barriers to Reproduction
  \begin{enumerate}
  \item Pre-zygotic: ecologically separated in space, temporally, sexually, mechanically, gametic incompatibility
  \item Incipient Species: a natural population that is more or less interfertile with another related population but is inhibited from interbreeding in nature by some specific barrier
  \item Post-zygotic: infertile organisms, embryos don't reach maturity, etc
  \item Speciation is a biproductive of divergence. Physical isolation then will inevitably diverge because mutations accumulate in populations. Geography is a key consideration in models of speciation
  \item Vicariance: population split by an extrinsic event (e.g Isthmus of Panama)
  \item Dispersal: Some species disperse to a new location (e.g birds migrate to another island)
  \item Darwin's Finches: Allopatry - vicariance or dispersal mediated isolation
    \begin{enumerate}
    \item First island appeared about 4.5 mya. And very few islands to start until 1.5 mya. Finches arose around 3 mya. Not many finch species until after many islands formed. Fascilitates isolation
    \end{enumerate}
  \item Sympatric Isolation: with gene flow still occuring
    \begin{enumerate}
    \item Chromosomal speciation - almost instantly. Chromosomal Rearrangement
    \item Chromosome configurations: Humans (diploid number is 46, haploid number is 23). Peaks on even numbers in plants - overrepresented. Some process of genome doubling. Plants have the ability to self-reproduce.
    \item Speciation with Gene flow: something must counteract homogenizing influence
      \begin{enumerate}
      \item Disruptive Selection: finches example of bill size and seed size availability
      \item Ecological Niche: Principle of Competitive Exclusion - can coexist if not competing for the same resources
      \item Niche expansion: especially common on islands - tree kangaroos example
      \item Adaptive Radiation: available ecological opportunity
      \end{enumerate}
    \end{enumerate}
  \end{enumerate}
\end{enumerate}






\end{document}