\documentclass{article}
\usepackage{Sweave}
\usepackage{mdframed}
\usepackage[small]{caption}
\setkeys{Gin}{width=0.8\textwidth}
\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm        
\oddsidemargin -0.04cm   
\evensidemargin -0.04cm
\textwidth 16.59cm
\textheight 21.94cm 
%\pagestyle{empty} %comment if want page numbers
\parskip 7.2pt
\renewcommand{\baselinestretch}{1.5}
\parindent 0pt


\begin{document}

\section*{Lecture 15: 25 Oct 2018}
\textbf{Andrew}
\large Evolution of Sex and Sexual Selection
Review session Monday 3-415pm in Yenching
\begin{enumerate}
\item Sex is an anomoaly
  \begin{enumerate}
  \item Twofold cost to males: if a female can asexually reproduce then each female can reproduce from there but if you need males, need to find a mate and then some of the offspring are males. Double the efficiency with asexual females. In theory, a hermaphrodite should sweep through a population - eliminate males. 
  \item Balancing Selection (balanced polymorphism): sickle cell anemia example
  \item Aggravation: spider example - male is killed and eaten 
  \item Disease
  \end{enumerate}
\item Asexuality is rare. Is facultative
  \begin{enumerate}
  \item short lived resource to be exploited to its maximum - asexuality arises. Ex. Aphids which is temporary but become sexual again at the end of summer
  \item Phylogenetic distribution of asexuality is evolutionarily short lived
  \end{enumerate}
\item Benefits of Sex
  \begin{enumerate}
  \item Asexual vs sexual in antibiotics example. Sex enhances evolvability (the rate at which a solutianary response can occur)
  \item Sex is favored in a highly variable environment. Climate change. 
  \item Red Queen Theory: species are all evolving just to stay in the same place. Lion vs zebra example
    \begin{enumerate}
    \item Parasites attack most common individuals so better to be rare. Sex increases diversity or `rareness'. 
    \item RA Fisher: sex rations are usually at parity. If one is in excess, the other is in demand. Good to be rare - more success
    \end{enumerate}
  \end{enumerate}
\item Departures from sex ratio parity
  \begin{enumerate}
  \item Trivers \& Willard: depends if you offspring will be better or worse than average
  \item Island of Rhum: Read deer in Scotland. Males fight amongst each other. Females will likely be mated, regardless of rank. High variance of male reproductive success but low variance in success in females. 
  \item When females are healthy, can produce big baby boys. But if not as healthy, then can produce low rank females.
  \item Opposum experiment
  \end{enumerate}
\item Angiospermy
  \begin{enumerate}
  \item Choosy Females - more costs
  \item Sexual Dimorphism: positively correlatd with strength of sexual selection
  \item Role Reversal: some species switch. seahorse example
  \end{enumerate}
\item Inter vs intra sexual selection
\item Sperm Competition: polygamous vs monogamous and ejaculate volume. Dragonfly example.
\item How does inter sexual selection arise?
  \begin{enumerate}
  \item Runaway Model: widow-tailed birds (Fisher again)
  

  \end{enumerate}




\end{enumerate}
\end{document}